version: 2
# scoverageのレポートを保存するよう設定

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/scala-generic-diff
    steps:
      - checkout
      - restore_cache:
          keys:
            - scala-generic-diff-
      - run:
          name: Run compile
          command: sbt 'project genericDiff' clean update compile
      - run:
          name: Run tests
          command: sbt 'project genericDiff' coverage test coverageReport
      - run:
          name: Aggregate coverage reports
          command: sbt 'project genericDiff' coverageAggregate && sbt 'project genericDiff' coveralls
      - save_cache:
          key: scala-generic-diff-
          paths:
            - /.sbt
            - /.ivy2
      - store_artifacts:
          path: ~/scala-generic-Diff/genericDiff/target/*/scoverage-report

